### ISSUE TITLE
Crockford code?

### ISSUE THREAD

**Issue by piecioshka** [hellfrom/monads#1]
Hi @hellfrom 

did you watched https://www.youtube.com/watch?v=b0EF0VTs9Dc ?
because I see similar code in this repo :smile:

**Comment by Darmikon** [comment]
Hi! Yes you are right I used Crockford's pattern. I watched [this link](https://www.youtube.com/watch?v=dkZFtimgAcM). But material in both videos seems to be the same. At the moment there is only one monad - `foreach` in this repository.
